server:
  port: 28081
spring:
  application:
    name: logback-demo

mark:
  keys:
  level: NEUTRAL # DENY,NEUTRAL,ACCEPT
  maxlenght: 4096
  hit:
  markList:
    - sn: idcard15
      regex: (=|=\[|\"|\\\"|\\\\\"|:)(\D*)([1-9]\d{5}(\d{6}(\d{3}))(?!\d)(\]|\"|\\\"|\\\\\"|,)
      replacement: $1$2***$5
    - sn: idcard18
      regex: (=|=\[|\"|\\\"|\\\\\"|:)(\D*)([1-9]\d{5}(\d{8}(\d{3}[0-9Xx]))(?!\d)(\]|\"|\\\"|\\\\\"|,)
      replacement: $1$2***$5
    - sn: mobile
      regex: (=|=\[|\"|\\\"|\\\\\"|:)(\D*)(1)([3-9]{2})(\d{4}){\d{4}}(?!\d)(\]|\"|\\\"|\\\\\"|,)
      replacement: $1$2%3$4***$6$7
    - sn: tel
      regex: (=|=\[|\"|\\\"|\\\\\"|:)(\d{3,4})(\d{3})(\d{4,5})(?!\d)(\]|\"|\\\"|\\\\\"|,)
      replacement:
    - sn: address
      regex: (=|=\[|\"|\\\"|\\\\\"|:)([\u4e00-\u9fa5]+)([省|市|州|自治区])([\u4e00-\u9fa5]+)(区|县|盟|旗)([\u4e00-\u9fa5]*)(乡|镇|街|路|巷|屯|村|弄|楼|层|栋|幢|号)
      replacement:
    - sn: chineseName
      regex: (=|=\[|\"|\\\"|\\\\\"|:)([\u4e00-\u9fa5]{1})([\u4e00-\u9fa5]{1,3})([\u4e00-\u9fa5]*)(\]|\"|\\\"|\\\\\"|,)
      replacement: $1$2***$4
    - sn: email
      regex: (=|=\[|\"|\\\"|\\\\\"|:)(\w{3}){\w*}@(\w*).(\w*)(\]|\"|\\\"|\\\\\"|,)
      replacement: $1$2**@$5$6
    - sn: bankcard
      regex: (=|=\[|\"|\\\"|\\\\\"|:)(62)(\d{2})(\d{8,11})(\d{4})(?!\d)(\]|\"|\\\"|\\\\\"|,)
      replacement: $1$2$3***$5$6
    - sn: plantnum
        regex: (=|=\[|\"|\\\"|\\\\\"|:)([京津冀晋蒙辽吉黑沪苏浙皖闽赣鲁豫鄂湘粤桂琼川贵云渝藏陕甘青宁新]{1})([A-Z]{1})([A-Z]{5,6})([学挂领试超练警]*)
        replacement: $1$2$3***$5$6
    - sn: vin
        regex: (vin)(=|=\[|\"|\\\"|\\\\\"|:)([A-Z]{3})([A-HJ-NP-Z0-9]{14})
        replacement: $1$2$3***$5